aider: Fixed unterminated triple-quoted string literal in `youtube_downloader.py`.
# Aider chat conversation:

USER: will@MacBook-Air YTDownloader % python youtube_downloader.py "https://www.youtube.com/playlist?list=PLXmi76euGSyyq1nw21U1M4tTsM0Zysayk" --download playlist
  File "/Users/will/Documents/Projects/Python Projects/YTDownloader/YTDownloader/youtube_downloader.py", line 58
    help_message = textwrap.dedent('''
                                   ^
SyntaxError: unterminated triple-quoted string literal (detected at line 69)

ASSISTANT: It seems like the `help_message` variable is not properly defined and the triple-quoted string literal is not terminated. This is causing the `SyntaxError`.

To fix this, we need to properly define the `help_message` variable and terminate the string literal.

Here is the change that needs to be made in the `youtube_downloader.py` file:

```python
youtube_downloader.py
<<<<<<< HEAD
    help_message = textwrap.dedent('''
=======
    help_message = textwrap.dedent('''
    Usage:
    ======
    python youtube_downloader.py <url> -d=<type>

    Examples:
    =========
    To download a video:
    python youtube_downloader.py "https://www.youtube.com/watch?v=5PS2p1AZzFY" -d=video

    To download a playlist:
    python youtube_downloader.py "https://www.youtube.com/playlist?list=PLXmi76euGSyyq1nw21U1M4tTsM0Zysayk" -d=playlist

    Have fun!
    ''')
>>>>>>> updated
```

This change will properly define the `help_message` variable and terminate the string literal, which should resolve the `SyntaxError`.